# Reference values from R for kycg's hypergeometric + BH implementation.
# Mirrors knowYourCG's calculate_fisher_pvalue(): phyper(m=nQ, n=nU-nQ, k=nD).

cases <- list(
  # nDQ, nQ, nD, nU  -- small, exactly enumerable
  c(5, 10, 20, 100),
  c(0, 10, 20, 100),
  c(10, 10, 20, 100),
  c(1, 3, 5, 10),
  # moderate
  c(150, 1000, 2000, 100000),
  c(20, 1000, 2000, 100000),
  c(500, 1000, 2000, 100000),
  # array-scale (HM450-ish universe)
  c(5000, 20000, 100000, 486427),
  c(1000, 20000, 100000, 486427),
  c(19000, 20000, 100000, 486427),
  # whole-genome sequencing scale: the far tail that underflows
  c(500000, 1000000, 5000000, 29000000),
  c(100000, 1000000, 5000000, 29000000),
  c(900000, 1000000, 5000000, 29000000),
  c(172414, 1000000, 5000000, 29000000),   # near the null expectation
  # degenerate / boundary
  c(0, 0, 100, 1000),
  c(100, 100, 100, 1000),
  c(1, 1, 1, 2)
)

cat("/* generated by tests/ref.R -- do not edit by hand */\n")
cat("static const hg_case_t HG_CASES[] = {\n")
for (cs in cases) {
  nDQ <- cs[1]; nQ <- cs[2]; nD <- cs[3]; nU <- cs[4]
  nDmQ  <- nD - nDQ
  nQmD  <- nQ - nDQ
  nUmDQ <- nU - nQ - nD + nDQ
  m <- nDQ + nQmD; n <- nUmDQ + nDmQ; k <- nDmQ + nDQ

  pvg <- phyper(nDQ - 1, m, n, k, lower.tail = FALSE, log.p = TRUE) / log(10)
  pvl <- phyper(nDQ,     m, n, k, lower.tail = TRUE,  log.p = TRUE) / log(10)
  pv2 <- min(min(pvg, pvl) + log10(2), 0)

  cat(sprintf("  {%d, %d, %d, %d, %s, %s, %s},\n",
              nDQ, nQ, nD, nU,
              format(pvg, digits = 17), format(pvl, digits = 17),
              format(pv2, digits = 17)))
}
cat("};\n\n")

# ---- BH reference -------------------------------------------------------
set.seed(42)
lp <- c(-300.5, -120.25, -50.1, -10.0, -3.3, -1.2, -0.5, -0.05, -0.001, 0)
p  <- 10^lp
q  <- p.adjust(p, method = "fdr")
cat("/* BH over 10 log10 p-values; expected log10(FDR) */\n")
cat("static const double BH_LOG10P[] = {")
cat(paste(format(lp, digits = 17), collapse = ", "))
cat("};\n")
cat("static const double BH_EXPECT[] = {")
cat(paste(format(log10(q), digits = 17), collapse = ", "))
cat("};\n")
