// SPDX-License-Identifier: AGPL-3.0-or-later
/**
 * This file is part of kycg.
 *
 * Copyright (C) 2026-present Wanding Zhou
 *
 * kycg is free software: you can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * kycg is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for
 * more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with kycg.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * Agreement tests for the hypergeometric tail and the BH correction.
 *
 * Expected values are R's own, produced by tests/ref.R (which calls phyper()
 * and p.adjust() directly) and pasted in below. Regenerate with:
 *
 *     Rscript tests/ref.R
 *
 * The cases deliberately span four regimes, because the failure modes differ:
 *
 *   - small universes, where the answer can be checked by hand;
 *   - array scale (~486K rows), the HM450 row space;
 *   - whole-genome scale (29M rows), where a naive lgamma-difference point
 *     mass loses roughly seven digits to cancellation;
 *   - the deep tail (log10 p around -584141), where any implementation that
 *     accumulates in linear space returns exactly 0 and where knowYourCG's
 *     own p.value column underflows.
 *
 * The last of these is the reason the whole pipeline is log-space, so it is
 * the case that matters most.
 */

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <stdint.h>

#include "hypergeo.h"

typedef struct {
  uint64_t nDQ, nQ, nD, nU;
  double greater, less, two_sided;
} hg_case_t;

/* generated by tests/ref.R -- do not edit by hand */
static const hg_case_t HG_CASES[] = {
  {5, 10, 20, 100, -1.5940640550458878, -0.0017114813104682619, -1.2930340593819065},
  {0, 10, 20, 100, 0, -1.0217451778853739, -0.72071518222139264},
  {10, 10, 20, 100, -7.9717062807040664, 0, -7.6706762850400851},
  {1, 3, 5, 10, -0.037788560889399761, -0.30102999566398109, 0},
  {150, 1000, 2000, 100000, -82.042563524256195, -4.2165393282134314e-84, -81.741533528592214},
  {20, 1000, 2000, 100000, -0.27483699693702368, -0.25250633458167526, 0},
  {500, 1000, 2000, 100000, -582.48730674701801, 0, -582.18627675135406},
  {5000, 20000, 100000, 486427, -53.759341415950388, -5.7933447637776532e-55, -53.458311420286407},
  {1000, 20000, 100000, 486427, 0, -890.96239677541985, -890.66136677975589},
  {19000, 20000, 100000, 486427, -12089.230555128532, 0, -12088.929525132868},
  {500000, 1000000, 5000000, 29000000, -127721.30435546626, 0, -127721.00332547059},
  {100000, 1000000, 5000000, 29000000, 0, -9415.5738048398252, -9415.2727748441612},
  {900000, 1000000, 5000000, 29000000, -584141.97390960029, 0, -584141.67287960462},
  {172414, 1000000, 5000000, 29000000, -0.30085130902040447, -0.30027579495678058, 0},
  {0, 0, 100, 1000, 0, 0, 0},
  {100, 100, 100, 1000, -139.80516438360223, 0, -139.50413438793825},
  {1, 1, 1, 2, -0.3010299956639812, 0, 0},
};

/* BH over 10 log10 p-values; expected log10(FDR) */
static const double BH_LOG10P[] = {-300.5, -120.25, -50.1, -10.0, -3.3, -1.2, -0.5, -0.05, -0.001, 0.0};
static const double BH_EXPECT[] = {-299.50000000000000000, -119.55102999566398125, -49.57712125471966402, -9.60205999132796251, -2.99897000433601857, -0.97815125038364359, -0.34509804001425681, 0.0, 0.0, 0.0};

/* Mixed absolute/relative bound: the deep-tail values are O(1e5), so a purely
 * absolute tolerance would be meaningless there, and a purely relative one
 * would be meaningless for the values that are legitimately 0. */
static int close_enough(double got, double want) {
  if (isnan(got) && isnan(want)) return 1;
  double diff = fabs(got - want);
  return diff <= 1e-9 + 1e-12 * fabs(want);
}

static int n_fail = 0;

static void check(const char *what, double got, double want) {
  if (!close_enough(got, want)) {
    printf("  FAIL %-40s got %.17g  want %.17g  (diff %.3g)\n",
           what, got, want, fabs(got - want));
    ++n_fail;
  }
}

int main(void) {
  size_t n_cases = sizeof(HG_CASES) / sizeof(HG_CASES[0]);
  double worst_rel = 0.0;

  for (size_t i = 0; i < n_cases; ++i) {
    const hg_case_t *c = &HG_CASES[i];
    char label[128];

    double g = kycg_hypergeo_log10p(c->nDQ, c->nQ, c->nD, c->nU, KYCG_ALT_GREATER);
    double l = kycg_hypergeo_log10p(c->nDQ, c->nQ, c->nD, c->nU, KYCG_ALT_LESS);
    double t = kycg_hypergeo_log10p(c->nDQ, c->nQ, c->nD, c->nU, KYCG_ALT_TWO_SIDED);

    snprintf(label, sizeof(label), "greater(%llu,%llu,%llu,%llu)",
             (unsigned long long)c->nDQ, (unsigned long long)c->nQ,
             (unsigned long long)c->nD, (unsigned long long)c->nU);
    check(label, g, c->greater);

    snprintf(label, sizeof(label), "less(%llu,%llu,%llu,%llu)",
             (unsigned long long)c->nDQ, (unsigned long long)c->nQ,
             (unsigned long long)c->nD, (unsigned long long)c->nU);
    check(label, l, c->less);

    snprintf(label, sizeof(label), "two.sided(%llu,%llu,%llu,%llu)",
             (unsigned long long)c->nDQ, (unsigned long long)c->nQ,
             (unsigned long long)c->nD, (unsigned long long)c->nU);
    check(label, t, c->two_sided);

    if (fabs(c->greater) > 1.0) {
      double rel = fabs(g - c->greater) / fabs(c->greater);
      if (rel > worst_rel) worst_rel = rel;
    }
  }

  /* The upper and lower tails must together account for the point mass:
   * P(X >= x) + P(X <= x) - P(X = x) = 1. Checked in linear space where the
   * numbers are representable, which is the regime this identity can be
   * evaluated in at all. */
  {
    double up = pow(10.0, kycg_lphyper_upper(5, 10, 90, 20));
    double lo = pow(10.0, kycg_lphyper_lower(5, 10, 90, 20));
    double pt = pow(10.0, kycg_ldhyper(5, 10, 90, 20));
    check("tail complement identity", up + lo - pt, 1.0);
  }

  /* BH, single stratum. */
  {
    size_t n = sizeof(BH_LOG10P) / sizeof(BH_LOG10P[0]);
    size_t *idx = malloc(n * sizeof(size_t));
    double *fdr = malloc(n * sizeof(double));
    for (size_t i = 0; i < n; ++i) idx[i] = i;
    kycg_bh_log10(BH_LOG10P, idx, n, fdr);
    for (size_t i = 0; i < n; ++i) {
      char label[64];
      snprintf(label, sizeof(label), "bh[%zu]", i);
      check(label, fdr[i], BH_EXPECT[i]);
    }
    free(idx); free(fdr);
  }

  /* BH must be order-invariant: shuffling the input rows may not change any
   * row's FDR. This is the property most likely to break if the step-up is
   * ever rewritten to work in place. */
  {
    static const double lp[6] = {-1.0, -5.0, -0.3, -20.0, -0.01, -2.0};
    size_t fwd[6] = {0, 1, 2, 3, 4, 5};
    size_t rev[6] = {5, 4, 3, 2, 1, 0};
    double a[6], b[6];
    kycg_bh_log10(lp, fwd, 6, a);
    kycg_bh_log10(lp, rev, 6, b);
    for (size_t i = 0; i < 6; ++i) {
      char label[64];
      snprintf(label, sizeof(label), "bh order-invariance[%zu]", i);
      check(label, a[i], b[i]);
    }
  }

  if (n_fail) {
    printf("  %d check(s) FAILED\n", n_fail);
    return 1;
  }
  printf("  all checks passed (worst relative error on tails: %.3g)\n", worst_rel);
  return 0;
}
