#!/bin/sh
# Regenerate src/registry.h by pinning the digests each channel publishes.
#
#   tools/make_registry.sh [tag] > src/registry.h
#
# Two channels, two publishers, two digest schemes -- kycg verifies against
# whatever the publisher actually signs rather than inventing its own.
#
#   Arrays (InfiniumAnnotation, git raw at a tag)
#     Layout: <base>/<tag>/<PLATFORM>/KYCG/{SHA256SUMS, <Set>.<date>.cm[.idx]}
#     We pin sha256(<PLATFORM>/KYCG/SHA256SUMS). Every individual file digest
#     chains from that one anchor, so the pin is a single line per platform and
#     adding a set upstream does not require regenerating anything but the
#     anchor. A platform not published at the tag gets a NULL anchor and cannot
#     be fetched.
#
#   Sequencing (Zenodo record per genome)
#     Zenodo has no manifest file to anchor, so there is nothing to chain from;
#     the record API lists each file with a size and an md5. We pin that list
#     verbatim, one entry per file. md5 is what Zenodo publishes and the only
#     digest it offers -- but because the value is compiled into the binary
#     rather than fetched alongside the file, it functions as a pin, not as a
#     claim the download gets to make about itself.
#
# Regenerating requires network but downloads nothing large: the array side
# fetches only SHA256SUMS files, and the Zenodo side only reads the JSON API.
set -eu

tag=${1:-v8}
base=${KYCG_IA_BASE_URL:-https://github.com/zhou-lab/InfiniumAnnotation/raw}

# Platforms carrying a KYCG/ directory in InfiniumAnnotation, with the size of
# the row space each one indexes -- the number of probes in its ordering.
#
# These are pinned rather than derived because they are the one fact a user
# needs *before* downloading anything: a .cm is only comparable to a query
# with the same row count, so showing the dimension next to each target is
# what makes it possible to pick the right one. Verified against the published
# .cm files; see DESIGN.md section 2.
#
# platform | rows
platforms="EPIC:866553 EPICv2:937690 HM27:27722 HM450:486427 \
Mammal40:38607 MM285:287692 MSA:284309"

# genome:zenodo_record:doi:rows   (rows = CpGs in cpg_nocontig.cr)
genomes="hg38:18175838:10.5281/zenodo.18175837:29401795 \
mm10:18175656:10.5281/zenodo.18175655:21867837"

cat <<EOF
/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Regenerate with:  tools/make_registry.sh $tag > src/registry.h
 *
 * Arrays: sha256(<PLATFORM>/KYCG/SHA256SUMS) at the pinned tag is the trust
 * anchor; every file digest chains from it. NULL anchor = not published.
 *
 * Sequencing: Zenodo publishes no manifest to anchor, so each file's size and
 * md5 are pinned individually, as reported by the record API.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026-present Wanding Zhou
 */
#ifndef _KYCG_REGISTRY_H
#define _KYCG_REGISTRY_H

#include <stdint.h>
#include <stddef.h>

#define KYCG_IA_BASE_URL   "$base"
#define KYCG_IA_TAG        "$tag"
#define KYCG_IA_SUMS_FILE  "SHA256SUMS"
#define KYCG_ZENODO_BASE   "https://zenodo.org/records"

/* One array platform's KYCG knowledgebase directory. */
typedef struct {
    const char *platform;
    uint64_t    rows;          /* probes in the platform's ordering */
    const char *sums_sha256;   /* sha256 of <platform>/KYCG/SHA256SUMS */
} kycg_array_reg_t;

static const kycg_array_reg_t KYCG_ARRAY_REGISTRY[] = {
EOF

for entry in $platforms; do
    plat=$(echo "$entry" | cut -d: -f1)
    nrow=$(echo "$entry" | cut -d: -f2)
    url="$base/$tag/$plat/KYCG/SHA256SUMS"
    sha=$(curl -sfL "$url" 2>/dev/null | shasum -a 256 | cut -d' ' -f1 || true)
    if [ -n "${sha:-}" ] && curl -sfL "$url" >/dev/null 2>&1; then
        printf '    { "%s", %s, "%s" },\n' "$plat" "$nrow" "$sha"
    else
        printf '    { "%s", %s, NULL },  /* not published at %s */\n' \
            "$plat" "$nrow" "$tag"
    fi
done

cat <<'EOF'
    { NULL, 0, NULL }
};

/* One file inside a Zenodo record. */
typedef struct {
    const char *name;
    uint64_t    size;
    const char *md5;
} kycg_zfile_t;

EOF

# Emit a file table per genome, then the genome table referring to them.
for g in $genomes; do
    genome=$(echo "$g" | cut -d: -f1)
    record=$(echo "$g" | cut -d: -f2)
    printf 'static const kycg_zfile_t KYCG_ZFILES_%s[] = {\n' "$genome"
    curl -sfL "https://zenodo.org/api/records/$record" 2>/dev/null | python3 -c '
import sys, json
try:
    d = json.load(sys.stdin)
except Exception:
    sys.exit(0)
for f in sorted(d.get("files", []), key=lambda x: x["key"]):
    ck = f.get("checksum", "")
    md5 = ck.split(":", 1)[1] if ":" in ck else ck
    print("    { \"%s\", %d, \"%s\" }," % (f["key"], f["size"], md5))
' || true
    printf '    { NULL, 0, NULL }\n};\n\n'
done

cat <<'EOF'
/* One genome's sequencing knowledgebase collection. */
typedef struct {
    const char        *genome;
    uint64_t           rows;      /* CpGs in cpg_nocontig.cr */
    const char        *record;    /* Zenodo record id */
    const char        *doi;
    const kycg_zfile_t *files;
} kycg_seq_reg_t;

static const kycg_seq_reg_t KYCG_SEQ_REGISTRY[] = {
EOF

for g in $genomes; do
    genome=$(echo "$g" | cut -d: -f1)
    record=$(echo "$g" | cut -d: -f2)
    doi=$(echo "$g" | cut -d: -f3)
    nrow=$(echo "$g" | cut -d: -f4)
    printf '    { "%s", %s, "%s", "%s", KYCG_ZFILES_%s },\n' \
        "$genome" "$nrow" "$record" "$doi" "$genome"
done

cat <<'EOF'
    { NULL, 0, NULL, NULL, NULL }
};

#endif /* _KYCG_REGISTRY_H */
EOF
