#!/usr/bin/env bash
## Generate src/registry.h from YAME's shared file table.
##
##   tools/make_registry.sh -o src/registry.h     (atomic; recommended)
##   tools/make_registry.sh --check               (CI: regenerate and compare)
##
## WHY THIS LIVES IN KYCG
##   kycg depends on YAME, so YAME cannot own kycg's struct definitions: a
##   field on kycg's own public type used to be a YAME commit. YAME keeps the
##   catalog (tools/registry/files.tsv) and the lookups (lib.sh); the
##   projection of that table into THIS repo's header is ours. See the
##   labjournal ROADMAP entry "each tool emits its own registry".
##
## WHAT IT PROJECTS
##   kycg's universe is three globs over store_path: the knowledgebase sets
##   under <target>/KYCG/, the whole-genome row lists, and the array probe
##   orderings. Everything else in the table belongs to another tool.
##
## OFFLINE. Reads the checked-in table and nothing else; no network, no cache.
## Regeneration is byte-reproducible, which is what --check asserts.
set -euo pipefail

## Byte-reproducibility is the whole contract here -- CI regenerates and
## compares -- so the collation every sort and comparison uses must not depend
## on the developer's locale. Without this, `sort` orders the tag summary one
## way under en_US.UTF-8 and another under C, and the header is "stale" on any
## machine whose locale differs from the one that last generated it.
export LC_ALL=C

cd "$(dirname "$0")/.."
. external/YAME/tools/registry/lib.sh

out=""; check=0
case ${1:-} in
  -o)      out=${2:?-o needs a path} ;;
  --check) check=1 ;;
  "")      ;;
  *)       echo "usage: $0 [-o src/registry.h | --check]" >&2; exit 2 ;;
esac

## Zenodo deposits are provenance for the whole-genome collections and are
## kycg's alone -- files.tsv deliberately does not carry them (design §2.8).
## genome<TAB>record<TAB>doi
zenodo() {
  cat <<'Z'
hg38	18175838	10.5281/zenodo.18175837
mm10	18175656	10.5281/zenodo.18175655
mm39		
Z
}
zen_field() { zenodo | /usr/bin/awk -F'\t' -v g="$1" -v i="$2" '$1==g{print $i}'; }

## A C string, or NULL for an empty cell.
cstr() { if [ -z "$1" ]; then printf 'NULL'; else printf '"%s"' "$1"; fi; }

## One kycg_file_t[] for a set of rows: name, url, digest, size.
emit_files() {   ## symbol glob...
  local sym=$1; shift
  printf 'static const kycg_file_t %s[] = {\n' "$sym"
  local row key
  while IFS= read -r row; do
    [ -n "$row" ] || continue
    key=$(field "$row" key)
    printf '    { "%s", "%s", "%s", %s },\n' \
      "$(basename "$(field "$row" store_path)")" \
      "$(url_of "$key")" "$(field "$row" sha256)" \
      "$(field "$row" size)"
  done < <(files_of "$@")
  printf '    { NULL, NULL, NULL, 0 }\n};\n\n'
}

emit() {
  cat <<'EOF'
/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Regenerate with:  tools/make_registry.sh -o src/registry.h
 * Check with:       tools/make_registry.sh --check
 *
 * A projection of YAME's shared file table (external/YAME/tools/registry/
 * files.tsv) into the shape kycg uses. The table names every file the suite
 * can fetch, keyed source@tag:remote_path; kycg takes the knowledgebase sets,
 * the whole-genome row lists and the array probe orderings, and nothing else.
 *
 * EVERY FILE CARRIES ITS OWN DIGEST, and that digest is what a download is
 * verified against. There is no directory anchor and no trust in a fetched
 * manifest: a file is what this header says it is, or it is discarded. A set
 * published upstream with no row here cannot be verified, so it is not
 * offered -- the table is the authority for what exists.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026-present Wanding Zhou
 */
#ifndef _KYCG_REGISTRY_H
#define _KYCG_REGISTRY_H

#include <stdint.h>
#include <stddef.h>

/* One fetchable file. `url` is built from the row's key by the host rule in
 * YAME's lib.sh, so kycg never spells a URL itself; `sha256` is the pin. */
typedef struct {
    const char *name;      /* basename, as it lands in the store directory */
    const char *url;
    const char *sha256;    /* what the download is verified against */
    uint64_t    size;      /* 0 when upstream publishes none */
} kycg_file_t;

/* One array platform. `sets` is <platform>/KYCG/, `comp` the probe ordering
 * that lands one level up and gives a row index its identity. */
typedef struct {
    const char        *platform;
    uint64_t           rows;     /* probes in the ordering */
    uint64_t           n_sets;   /* .cm sets, excluding .idx sidecars */
    const kycg_file_t *sets;
    const kycg_file_t *comp;
} kycg_array_reg_t;

/* One whole-genome collection. `comp` is cpg_nocontig.cr, which since
 * genomes v4 comes from the genome repository rather than the knowledgebase
 * one -- the key on its row says so, and kycg no longer has to care. */
typedef struct {
    const char        *genome;
    uint64_t           rows;     /* CpGs in cpg_nocontig.cr */
    uint64_t           n_sets;
    const char        *record;   /* Zenodo, provenance only; may be NULL */
    const char        *doi;
    const kycg_file_t *sets;
    const kycg_file_t *comp;
} kycg_seq_reg_t;

EOF

  ## ---- per-collection file tables ------------------------------------- ##
  local plat gen
  for plat in $(files_of '*/*.ordering.tsv.gz' | cut -f2 | cut -d/ -f1); do
    emit_files "KYCG_SETS_$plat" "$plat/KYCG/*"
    emit_files "KYCG_COMP_$plat" "$plat/*.ordering.tsv.gz"
  done
  for gen in $(files_of '*/cpg_nocontig.cr' | cut -f2 | cut -d/ -f1); do
    emit_files "KYCG_SETS_$gen" "$gen/KYCG/*"
    emit_files "KYCG_COMP_$gen" "$gen/cpg_nocontig.cr"
  done

  ## ---- the two registries ---------------------------------------------- ##
  printf 'static const kycg_array_reg_t KYCG_ARRAY_REGISTRY[] = {\n'
  local row nsets
  while IFS= read -r row; do
    plat=$(field "$row" store_path); plat=${plat%%/*}
    nsets=$(files_of "$plat/KYCG/*" | cut -f2 | grep -c '\.cm$' || true)
    printf '    { "%s", %s, %s, KYCG_SETS_%s, KYCG_COMP_%s },\n' \
      "$plat" "$(field "$row" rows)" "$nsets" "$plat" "$plat"
  done < <(files_of '*/*.ordering.tsv.gz')
  printf '    { NULL, 0, 0, NULL, NULL }\n};\n\n'

  printf 'static const kycg_seq_reg_t KYCG_SEQ_REGISTRY[] = {\n'
  while IFS= read -r row; do
    gen=$(field "$row" store_path); gen=${gen%%/*}
    nsets=$(files_of "$gen/KYCG/*" | cut -f2 | grep -c '\.cm$' || true)
    printf '    { "%s", %s, %s, %s, %s, KYCG_SETS_%s, KYCG_COMP_%s },\n' \
      "$gen" "$(field "$row" rows)" "$nsets" \
      "$(cstr "$(zen_field "$gen" 2)")" "$(cstr "$(zen_field "$gen" 3)")" \
      "$gen" "$gen"
  done < <(files_of '*/cpg_nocontig.cr')
  printf '    { NULL, 0, 0, NULL, NULL, NULL, NULL }\n};\n\n'

  ## ---- what this build can verify, for --version ------------------------ ##
  ## Per-row tags mean there is no single pinned tag any more; state each
  ## source and the tag its rows carry, which is what a user can check.
  printf '/* The upstream sources this build carries rows from, and their tags. */\n'
  printf '#define KYCG_REGISTRY_TAGS "%s"\n\n' \
    "$(files_of '*/KYCG/*' '*/cpg_nocontig.cr' '*/*.ordering.tsv.gz' |
       cut -f1 | /usr/bin/awk -F'[@:]' '{print $1"@"$2}' |
       sed 's#^[^/]*/##' | sed 's/_[a-z0-9]*@/@/' | sort -u | tr '\n' ' ' |
       sed 's/ $//')"

  printf '#endif /* _KYCG_REGISTRY_H */\n'
}

if [ "$check" = 1 ]; then
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  if cmp -s "$tmp" src/registry.h; then
    echo "registry: src/registry.h is current"
  else
    echo "registry: src/registry.h is STALE -- run tools/make_registry.sh -o src/registry.h" >&2
    diff -u src/registry.h "$tmp" | head -20 >&2
    exit 1
  fi
elif [ -n "$out" ]; then
  ## Atomic: a failed run never leaves a half-written header that compiles.
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  mv "$tmp" "$out"
  trap - EXIT
  echo "registry: wrote $out"
else
  emit
fi
