#!/usr/bin/env bash
## Compile what each knowledgebase set IS into src/kbinfo.h.
##
##   tools/make_kbinfo.sh -o src/kbinfo.h     (atomic; recommended)
##   tools/make_kbinfo.sh --check             (CI: regenerate and compare)
##
## The prose comes from YAME's shared table, the same rows the registry is
## projected from -- one description per set for the whole suite, rather than
## kycg keeping a second copy that can disagree. (It used to live in
## data/knowledgebases.tsv; that file folded into files.tsv at the v1.50 bump.)
##
## Keyed on the SET name -- the part of a filename before the first dot -- so
## one entry covers every genome and platform that publishes that set. The
## browser has to describe a set while drawing a frame, so this is compiled in
## rather than read at run time.
##
## Needs no network.
set -euo pipefail

cd "$(dirname "$0")/.."
. external/YAME/tools/registry/lib.sh

out=""; check=0
case ${1:-} in
  -o)      out=${2:?-o needs a path} ;;
  --check) check=1 ;;
  "")      ;;
  *)       echo "usage: $0 [-o src/kbinfo.h | --check]" >&2; exit 2 ;;
esac

## A C string body: backslashes and quotes escaped, newlines flattened.
cesc() { printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g' | tr '\n' ' '; }

emit() {
  cat <<'EOF'
/* kbinfo.h -- GENERATED by tools/make_kbinfo.sh. Do not edit.
 *
 * Regenerate with:  tools/make_kbinfo.sh -o src/kbinfo.h
 *
 * What a knowledgebase set is, beyond its name, for the browser's info pane.
 * Projected from YAME's shared file table (external/YAME/tools/registry/
 * files.tsv), which is the suite's single source of set descriptions.
 *
 * Keyed on the set name -- the part of a filename before the first dot -- so a
 * single entry covers every genome and platform that publishes that set.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026-present Wanding Zhou
 */
#ifndef _KYCG_KBINFO_H
#define _KYCG_KBINFO_H

#include <string.h>

typedef struct {
    const char *set;
    const char *collections;  /* comma-separated, e.g. "hg38,mm10,EPIC" */
    const char *title;
    const char *description;
    const char *source;
    const char *citation;
} kycg_kbinfo_t;

static const kycg_kbinfo_t KYCG_KBINFO[] = {
EOF

  ## One row per distinct set name, in first-seen order. awk does the grouping
  ## in one pass; the shell would re-scan the table once per set.
  files_of '*/KYCG/*' | /usr/bin/awk -F'\t' '
    {
      path = $2
      sub(/^[^\/]*\//, "", path); sub(/^KYCG\//, "", path)
      if (path !~ /\.cm$/) next            # .idx sidecars describe nothing
      set = path; sub(/\..*$/, "", set)
      coll = $2; sub(/\/.*$/, "", coll)
      if (!(set in seen)) { seen[set] = ++n; order[n] = set
                            title[set] = $7; desc[set] = $8
                            src[set] = $9; cit[set] = $10 }
      if (index("," colls[set] ",", "," coll ",") == 0)
        colls[set] = (colls[set] == "" ? coll : colls[set] "," coll)
    }
    END { for (i = 1; i <= n; i++) { s = order[i]
            printf "%s\t%s\t%s\t%s\t%s\t%s\n",
                   s, colls[s], title[s], desc[s], src[s], cit[s] } }' |
  while IFS=$'\t' read -r set coll title desc src cit; do
    printf '    { "%s", "%s",\n      "%s",\n      "%s",\n      "%s",\n      "%s" },\n' \
      "$(cesc "$set")" "$(cesc "$coll")" "$(cesc "$title")" \
      "$(cesc "$desc")" "$(cesc "$src")" "$(cesc "$cit")"
  done

  cat <<'EOF'
    { NULL, NULL, NULL, NULL, NULL, NULL }
};

/** What is this set? NULL when nothing is recorded. */
static inline const kycg_kbinfo_t *kycg_kbinfo_find(const char *set) {
    if (!set || !*set) return NULL;
    for (const kycg_kbinfo_t *k = KYCG_KBINFO; k->set; ++k)
        if (strcmp(k->set, set) == 0) return k;
    return NULL;
}

#endif /* _KYCG_KBINFO_H */
EOF
}

if [ "$check" = 1 ]; then
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"
  cmp -s "$tmp" src/kbinfo.h && echo "kbinfo: src/kbinfo.h is current" || {
    echo "kbinfo: src/kbinfo.h is STALE -- run tools/make_kbinfo.sh -o src/kbinfo.h" >&2
    exit 1; }
elif [ -n "$out" ]; then
  tmp=$(mktemp); trap 'rm -f "$tmp"' EXIT
  emit > "$tmp"; mv "$tmp" "$out"; trap - EXIT
  echo "kbinfo: wrote $out"
else
  emit
fi
