/* registry.h -- GENERATED by tools/make_registry.sh. Do not edit.
 *
 * Regenerate with:  tools/make_registry.sh v8 > src/registry.h
 *
 * Arrays: sha256(<PLATFORM>/KYCG/SHA256SUMS) at the pinned tag is the trust
 * anchor; every file digest chains from it. NULL anchor = not published.
 *
 * Set counts are pinned too. A tag is immutable, so the number of sets it
 * publishes is a fixed fact about it -- there is nothing to discover at run
 * time, and the overview can show have/total without touching the network.
 *
 * Whole genome: the same, anchored on sha256(SHA256SUMS) in KYCGKB_<genome>
 * at its own tag. File sizes are pinned alongside for display only; nothing
 * depends on them, so a set added upstream needs no rebuild.
 *
 * Zenodo keeps the DOI and remains the citable archive. It is recorded here as
 * provenance and is no longer the fetch path.
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * Copyright (C) 2026-present Wanding Zhou
 */
#ifndef _KYCG_REGISTRY_H
#define _KYCG_REGISTRY_H

#include <stdint.h>
#include <stddef.h>

#define KYCG_IA_BASE_URL   "https://github.com/zhou-lab/InfiniumAnnotation/raw"
#define KYCG_IA_TAG        "v8"
#define KYCG_IA_SUMS_FILE  "SHA256SUMS"
#define KYCG_KB_BASE_URL   "https://github.com/zhou-lab"
#define KYCG_ZENODO_BASE   "https://zenodo.org/records"

/* One array platform's KYCG knowledgebase directory. */
typedef struct {
    const char *platform;
    uint64_t    rows;          /* probes in the platform's ordering */
    uint64_t    n_sets;        /* .cm sets published at this tag */
    const char *sums_sha256;   /* sha256 of <platform>/KYCG/SHA256SUMS */
    /* The probe ordering sits one level up, under the platform's own
     * manifest, and is fetched alongside any set: it is what gives a row
     * index a probe name, so a set without it is a column of anonymous bits. */
    const char *plat_sums_sha256; /* sha256 of <platform>/SHA256SUMS */
} kycg_array_reg_t;

static const kycg_array_reg_t KYCG_ARRAY_REGISTRY[] = {
    { "EPIC", 866553, 17, "1678294f10134013db3fe274dfeb5243cd5e4352d40e01ef50528c91ac3b077b", "a50d593bb904ab30e7602fb62ff404fa4d639bf951712dda4899eb8d543c6c8c" },
    { "EPICv2", 937690, 16, "82c17bbc0b59fbf96545ea029cdc089a19214395d8d3f6e6826ee161b8b8eb17", "06139afa41798e1655b7a237903869352b67aaebc8c7be33a1410046500ed842" },
    { "HM27", 27722, 15, "450bdb2bb74d152ba8d8b96646e6976122ebe00900d41e7aa67ebcadcf739b68", "653a6ef7982d7726688ce7b63083fd3ab1322711a01a400117faba8d3d833c37" },
    { "HM450", 486427, 18, "27e4d8ef73bcd1c8b75ddb0fc203e17218bd5de1b05e0bfc847b217621c308bf", "6fd4845dae5c668f16b1fd0343b8e3eb7500507856384cccf4f9fc1a84871500" },
    { "Mammal40", 38607, 15, "f49d45d83eac05f556595980aadba6cce39ee64172050f065a7b2137b73ea351", "03a571de82ca657a91f3a2905ae9a8f5ac04601a8eca486366146e857aa71cbf" },
    { "MM285", 287692, 17, "2cb53129949cfce5f8149c6ab1321069f30a236757a3f4095c2e5e00b3c141e9", "5edd9172be38121d1c0f05638a16d208725c68efdb0224e693d879f2e31c531d" },
    { "MSA", 284309, 32, "cc63264354f71f436e7aa4e7b9820430461e6923d657c54a24bb03cca4682db5", "68198ff2da93346a3d43e5191f0eb7b1db636859780bd794e2a3776eded3175b" },
    { NULL, 0, 0, NULL, NULL }
};

/* A published file size, for display only -- never for correctness. */
typedef struct {
    const char *name;
    uint64_t    size;
} kycg_fsize_t;

static const kycg_fsize_t KYCG_SIZES_hg38[] = {
    { "ABCompartment.20220911.cm", 9763 },
    { "Blacklist.20220304.cm", 3142 },
    { "CGI.20220904.cm", 206746 },
    { "CTCFbind.20220911.cm", 163001 },
    { "Centromere.20221129.cm", 347 },
    { "ChromHMM.20220303.cm", 529428 },
    { "ChromHMMfullStack.20230515.cm", 7086738 },
    { "Chromosome.20221129.cm", 298 },
    { "ChromosomeXY.20230901.cm", 99 },
    { "HM.20221013.cm", 7540196 },
    { "HM.20221013.cm.idx", 1741 },
    { "ImprintingDMR.20220818.cm", 907 },
    { "IntermediateMeth.20221121.cm", 26683 },
    { "IntermediateMethS.20221121.cm", 18515 },
    { "MetagenePC.20220911.cm", 2971260 },
    { "MetagenePC.20220911.cm.idx", 712 },
    { "PMD.20220911.cm", 18325 },
    { "REMCChromHMM.20220911.cm", 490826 },
    { "RoadMapNegGeneExpCpG.20220814.cm", 463285 },
    { "RoadMapPosGeneExpCpG.20220814.cm", 570095 },
    { "TFBS.20220921.cm", 90986293 },
    { "TFBS.20220921.cm.idx", 27056 },
    { "TFBSrm.20221005.cm", 82231076 },
    { "TFBSrm.20221005.cm.idx", 23731 },
    { "Tetranuc2.20220321.cm", 9086753 },
    { "TiSigBLUEPRINT.20221209.cm", 26949077 },
    { "TiSigBLUEPRINT.20221209.cm.idx", 22418 },
    { "TiSigBrain.20221209.cm", 52404903 },
    { "TiSigBrain.20221209.cm.idx", 13414 },
    { "TiSigLoyfer.20221209.cm", 28806752 },
    { "TiSigLoyfer.20221209.cm.idx", 16421 },
    { "Win100k.20220228.cm", 169101 },
    { "XCILinkedWGBS.20221121.cm", 12552 },
    { "XCILinkedWGBSSorted.20221121.cm", 16744 },
    { "cpg_nocontig.cr", 30318472 },
    { "nFlankCG.20220321.cm", 11529528 },
    { "nFlankCG100.20231025.cm", 10120992 },
    { "nFlankCG50.20231025.cm", 7572753 },
    { "rmsk1.20220307.cm", 4645990 },
    { "rmsk1.20220307.cm.idx", 361 },
    { "rmsk2.20220321.cm", 5749686 },
    { "rmsk2.20220321.cm.idx", 1212 },
    { NULL, 0 }
};

static const kycg_fsize_t KYCG_SIZES_mm10[] = {
    { "Blacklist.20220304.cm", 636 },
    { "CGI.20220904.cm", 122892 },
    { "ChromHMM.20220318.cm", 878195 },
    { "ChromHMM.20220414.cm", 877986 },
    { "ChromHMMfullStack.20231222.cm", 6409786 },
    { "Chromosome.20240119.cm", 269 },
    { "ChromosomeXY.20230901.cm", 95 },
    { "EnsRegBuild.20220710.cm", 1019167 },
    { "EnsRegBuild.20220710.cm.idx", 146 },
    { "EvoCons.20220314.cm", 115742 },
    { "GCfrac.20220323.cm", 19989460 },
    { "GeneFeatures.20220710.cm", 1476841 },
    { "GeneFeatures.20220710.cm.idx", 123 },
    { "HM.20221013.cm", 5896537 },
    { "HM.20221013.cm.idx", 1632 },
    { "MetagenePC.20220911.cm", 2487844 },
    { "MetagenePC.20220911.cm.idx", 709 },
    { "PMD.20220911.cm", 16659 },
    { "TFBS.20220922.cm", 56669024 },
    { "TFBS.20220922.cm.idx", 13700 },
    { "TFBSFreq.20220922.cm", 3895475 },
    { "TFBSrm.20221005.cm", 53395935 },
    { "TFBSrm.20221005.cm.idx", 12454 },
    { "Tetranuc2.20220321.cm", 6838695 },
    { "Tetranuc4.20220321.cm", 13157336 },
    { "UCSCEnsemblRegulatory.20220727.cm", 639680 },
    { "Win100k.20220228.cm", 154709 },
    { "Win1m.20230709.cm", 16962 },
    { "Win30k.20220228.cm", 513471 },
    { "cpg_nocontig.cr", 23825886 },
    { "kmer10.20231109.cm", 52445331 },
    { "nFlankCG.20220321.cm", 7763796 },
    { "nFlankCG100.20231025.cm", 6787893 },
    { "nFlankCG50.20231025.cm", 5037900 },
    { "rmsk1.20220321.cm", 3321298 },
    { "rmsk1.20220321.cm.idx", 374 },
    { "rmsk2.20220321.cm", 4623244 },
    { "rmsk2.20220321.cm.idx", 1152 },
    { NULL, 0 }
};

/* One genome's whole-genome knowledgebase collection.
 *
 * `sums_sha256` is the trust anchor, exactly as for arrays. `record` and `doi`
 * point at the Zenodo deposit, which remains the citable archive but is no
 * longer where kycg fetches from. */
typedef struct {
    const char        *genome;
    uint64_t           rows;      /* CpGs in cpg_nocontig.cr */
    uint64_t           n_sets;    /* .cm sets published at this tag */
    const char        *repo;      /* GitHub repository name */
    const char        *tag;       /* pinned tag */
    const char        *sums_sha256;
    const char        *record;    /* Zenodo record id, provenance only */
    const char        *doi;
    const kycg_fsize_t *sizes;
} kycg_seq_reg_t;

static const kycg_seq_reg_t KYCG_SEQ_REGISTRY[] = {
    { "hg38", 29401795, 32, "KYCGKB_hg38", "v2", "8e0594ade2936a7b837306cec8e4d29bb9028a6a3be5b2cdbd372af7c16f650a", "18175838", "10.5281/zenodo.18175837", KYCG_SIZES_hg38 },
    { "mm10", 21867837, 29, "KYCGKB_mm10", "v1", "0693eb6d7e173c04e083c48c41eedc593af96a8ac78c80e8cfd2b24b71c25d3a", "18175656", "10.5281/zenodo.18175655", KYCG_SIZES_mm10 },
    { NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL }
};

#endif /* _KYCG_REGISTRY_H */
